### ISSUE TITLE
1.3.12 won't compile on centos 5.3 

### ISSUE THREAD

**Issue by naox** [sparklemotion/sqlite3-ruby#196]
```
user@sv1 [/home/user]# gem install sqlite3 -v '1.3.11'
Fetching: sqlite3-1.3.11.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.11
1 gem installed

user@sv1 [/home/user]# gem install sqlite3 -v '1.3.12'
Fetching: sqlite3-1.3.12.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    /usr/share/ruby-2.2.2/bin/ruby -r ./siteconf20161014-5389-o0y26n.rb extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for rb_integer_pack()... yes
checking for sqlite3_initialize()... no
checking for sqlite3_backup_init()... no
checking for sqlite3_column_database_name()... no
checking for sqlite3_enable_load_extension()... no
checking for sqlite3_load_extension()... no
checking for sqlite3_open_v2()... no
checking for sqlite3_prepare_v2()... no
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling sqlite3.c
compiling statement.c
compiling database.c
database.c: In function ‘initialize’:
database.c:105:7: error: ‘flags’ undeclared (first use in this function)
database.c:105:7: note: each undeclared identifier is reported only once for each function it appears in
database.c: In function ‘db_filename’:
database.c:837:9: warning: assignment makes pointer from integer without a cast [enabled by default]
make: *** [database.o] Błąd 1

make failed, exit code 2

Gem files will remain installed in /home/user/.gems/2.2/gems/sqlite3-1.3.12 for inspection.
Results logged to /home/user/.gems/2.2/extensions/x86_64-linux/2.2.0-static/sqlite3-1.3.12/gem_make.out
```

**Comment by tenderlove** [comment]
I don't have CentOS 5.3 to test with.  Can you please send a patch, or find the commit that broke compatibility?  Thank you!

**Comment by riyengar8** [comment]
FWIW, it appears to me that this commit broke compilation on my installation of centos 5:

9247a947c34a175a4a9b1b497c252273b905ea20

My C skills are not great, but it appears to me that the problem is that `flags` is being declared within a preprocessor conditional.

If I move `flags` outside of the `#ifdef` preprocessor conditional, I can get the gem to compile.

Hope this helps.

**Comment by tenderlove** [comment]
@riyengar8 that makes sense, thank you!  I'll fix it.

**Comment by tenderlove** [comment]
Should be fixed in 3ed928c18541e9d4be284ab7fbbf1e03601efa55.  Though please note that version 2 of the SQLite3 gem will require that libsqlite have `sqlite3_open_v2`, or it won't compile!
