### ISSUE TITLE
sqlite3 unable to install on Yosemite

### ISSUE THREAD

**Issue by cheunghy** [sparklemotion/sqlite3-ruby#157]
The log:
```
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
	ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150527-30935-1cv9vcq.rb extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... no
checking for rb_integer_pack()... no
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... no
checking for sqlite3_enable_load_extension()... no
checking for sqlite3_load_extension()... no
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling backup.c
compiling database.c
compiling exception.c
compiling sqlite3.c
sqlite3.c:35:20: warning: implicit declaration of function 'RBIGNUM' is invalid in C99 [-Wimplicit-function-declaration]
  const long len = RBIGNUM_LEN(value);
                   ^
sqlite3.c:33:27: note: expanded from macro 'RBIGNUM_LEN'
#   define RBIGNUM_LEN(x) RBIGNUM(x)->len
                          ^
sqlite3.c:35:20: error: member reference type 'int' is not a pointer
  const long len = RBIGNUM_LEN(value);
                   ^~~~~~~~~~~~~~~~~~
sqlite3.c:33:39: note: expanded from macro 'RBIGNUM_LEN'
#   define RBIGNUM_LEN(x) RBIGNUM(x)->len
                          ~~~~~~~~~~  ^
sqlite3.c:40:19: error: use of undeclared identifier 'SIZEOF_BDIGITS'
  if (len > 63 / (SIZEOF_BDIGITS * CHAR_BIT) + 1) return 0;
                  ^
sqlite3.c:41:20: error: use of undeclared identifier 'SIZEOF_BDIGITS'
  if (len == 63 / (SIZEOF_BDIGITS * CHAR_BIT) + 1) {
                   ^
sqlite3.c:42:11: error: unknown type name 'BDIGIT'
    const BDIGIT *digits = RBIGNUM_DIGITS(value);
          ^
sqlite3.c:42:28: warning: implicit declaration of function 'RBIGNUM_DIGITS' is invalid in C99 [-Wimplicit-function-declaration]
    const BDIGIT *digits = RBIGNUM_DIGITS(value);
                           ^
sqlite3.c:43:5: error: use of undeclared identifier 'BDIGIT'
    BDIGIT blast = digits[len-1];
    ^
sqlite3.c:44:5: error: use of undeclared identifier 'BDIGIT'
    BDIGIT bmax = (BDIGIT)1UL << (63 % (CHAR_BIT * SIZEOF_BDIGITS));
    ^
sqlite3.c:45:9: error: use of undeclared identifier 'blast'
    if (blast > bmax) return 0;
        ^
sqlite3.c:45:17: error: use of undeclared identifier 'bmax'; did you mean 'fmax'?
    if (blast > bmax) return 0;
                ^~~~
                fmax
/usr/include/math.h:546:15: note: 'fmax' declared here
extern double fmax(double, double);
              ^
sqlite3.c:46:9: error: use of undeclared identifier 'blast'
    if (blast == bmax) {
        ^
sqlite3.c:46:18: error: use of undeclared identifier 'bmax'; did you mean 'fmax'?
    if (blast == bmax) {
                 ^~~~
                 fmax
/usr/include/math.h:546:15: note: 'fmax' declared here
extern double fmax(double, double);
              ^
2 warnings and 10 errors generated.
make: *** [sqlite3.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/sqlite3-1.3.10/gem_make.out
```

**Comment by cheunghy** [comment]
This is due to my ruby installation.
Now it installs fine.
Thanks.

**Comment by pvdb** [comment]
Hey @cheunghy,

You wrote:
> This is due to my ruby installation.
> Now it installs fine.

Exactly what was wrong with your Ruby installation?  And how did you go about fixing it?  Thanks!

**Comment by cheunghy** [comment]
I installed ruby with source code, and I don't know exactly what's wrong
I fix it by using rbenv.

Thanks

**Comment by pvdb** [comment]
Thanks, @cheunghy - do you by any chance remember which version of Ruby was originally causing the issue, and which version of `rbenv` Ruby you installed to fix it?

**Comment by cheunghy** [comment]
both 2.2.2
What trouble you encountered?

**Comment by pvdb** [comment]
> What trouble you encountered?

It turned out to be the issue reported/documented here:

https://gist.github.com/zzak/695d1e25ec13d62ca671#gistcomment-1364746

Version `1.3.8` of `sqlite3` doesn't work with Ruby `2.2.x` so I had to upgrade to version `1.3.10` and everything works fine, even with older versions of Ruby (I tested the latest `sqlite3` against Ruby `2.0.x`, `2.1.x` and `2.2.x`)

**Comment by Hotinly** [comment]
@zhangkaiyulw  @pvdb  Can you fix the answer for help me, I got the same issue.
