### ISSUE TITLE
backup.c fails to compile on OSX 10.8.2 with sqlite 3.7.12

### ISSUE THREAD

**Issue by sentience** [sparklemotion/sqlite3-ruby#78]
I’m trying to perform an initial bundle install in a new (empty) Rails application, and it’s tripping up at the point of installing the sqlite3 gem:

```
/Users/kyank/.rvm/rubies/ruby-1.9.3-p362/bin/ruby extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... no
checking for sqlite3_enable_load_extension()... no
checking for sqlite3_load_extension()... no
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make
compiling backup.c
In file included from ./sqlite3_ruby.h:51,
                 from backup.c:3:
./backup.h:7: error: expected specifier-qualifier-list before ‘sqlite3_backup’
backup.c: In function ‘initialize’:
backup.c:63: error: ‘sqlite3_backup’ undeclared (first use in this function)
backup.c:63: error: (Each undeclared identifier is reported only once
backup.c:63: error: for each function it appears in.)
backup.c:63: error: ‘pBackup’ undeclared (first use in this function)
backup.c:74: warning: implicit declaration of function ‘sqlite3_backup_init’
backup.c:77: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c: In function ‘step’:
backup.c:101: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c:102: warning: implicit declaration of function ‘sqlite3_backup_step’
backup.c:102: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c: In function ‘finish’:
backup.c:115: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c:116: warning: implicit declaration of function ‘sqlite3_backup_finish’
backup.c:116: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c:117: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c: In function ‘remaining’:
backup.c:133: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c:134: warning: implicit declaration of function ‘sqlite3_backup_remaining’
backup.c:134: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c: In function ‘pagecount’:
backup.c:149: error: ‘sqlite3BackupRuby’ has no member named ‘p’
backup.c:150: warning: implicit declaration of function ‘sqlite3_backup_pagecount’
backup.c:150: error: ‘sqlite3BackupRuby’ has no member named ‘p’
make: *** [backup.o] Error 1
```

sqlite3 version is 3.7.12, which I believe is what came included with my OSX 10.8.2 system.

Any ideas? All the advice I can find elsewhere are old threads advising the use of MacPorts (!!) to upgrade to a more recent version of sqlite3. I’m pretty sure the version I have should me more than sufficient.
